[package]
name = "matrix_multiply_example"
version = "0.1.0"
edition = "2021"

[dependencies]
#rand = "0.8.5"
#vulkano = "0.34.1"
#vulkano-shaders = "0.34.0"
vulkano = "0.24.0"
vulkano-shaders = "0.24.0"
rand = "0.8.4"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
